import { GameSet } from "./GamePage";

const API_MOCK: GameSet[] = [
  {
    question: "select animals",
    all_words: [
      "hole",
      "sofa",
      "pear",
      "tiger",
      "oatmeal",
      "square",
      "nut",
      "cub",
      "shirt",
      "tub",
      "passenger",
      "cow",
    ],
    good_words: ["tiger", "cow"],
  },
  {
    question: "select frontend frameworks",
    all_words: [
      "Spring",
      "Angular",
      "React 💖",
      "Knockout",
      "ASP.NET",
      "Django",
      "AWS",
      "WPF",
      "Groovy",
      "Jenkins",
      "WSL",
      "MacOS",
      "Ubuntu",
    ],
    good_words: ["Angular", "React 💖", "Knockout"],
  },
  {
    question: "select bmw models",
    all_words: [
      "E92 💖",
      "F10",
      "G30",
      "E46",
      "S3",
      "A8",
      "X3",
      "95 Aero",
      "S40",
      "XC90",
    ],
    good_words: ["E92 💖", "F10", "G30", "E46"],
  },
  {
    question: "select colors",
    all_words: [
      "jeans",
      "existence",
      "ink",
      "red",
      "blue",
      "yellow",
      "laugh",
      "behavior",
      "expansion",
      "white",
      "black",
      "cakes",
    ],
    good_words: ["red", "blue", "yellow", "white", "black"],
  },
  {
    question: "select vehicles",
    all_words: [
      "belief",
      "wire",
      "car",
      "bus",
      "star",
      "river",
      "hat",
      "skirt",
      "train",
    ],
    good_words: ["car", "bus", "train"],
  },
];

export { API_MOCK };
